name: Keep Render app awake

on:
  schedule:
    # Every 5 minutes
    - cron: "*/5 * * * *"
  workflow_dispatch:  # allow manual trigger from Actions tab

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render health endpoint
        run: |
          URL="https://knowledgebase-chatbot.onrender.com/health"
          echo "Pinging $URL ..."
          curl -fsS --max-time 10 "$URL" || echo "Ping failed (service may be sleeping, will retry on next run)"
