name: Keep Render app awake

on:
  schedule:
    # Run every 5 minutes
    - cron: "*/5 * * * *"
  workflow_dispatch: {}  # allow manual run from GitHub UI
  push:
    paths:
      - ".github/workflows/keepalive.yml"


jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 4
    steps:
      - name: Ping health endpoint
        run: |
          URL="https://knowledgebase-chatbot.onrender.com/health"
          # Random small delay so multiple repos don’t collide
          sleep $((RANDOM % 20))
          echo "Pinging $URL ..."
          curl -fsS -m 10 "$URL" || echo "Ping failed (will try again next run)"
