# File: .github/workflows/keepalive.yml
#
# Pings your Render app every 5 minutes so the free instance
# doesn’t go to sleep. This costs $0 on GitHub Actions.
#
# Replace the URL below with your service URL if it’s different.

name: Keepalive (Render)

on:
  schedule:
    - cron: "*/5 * * * *"   # every 5 minutes (Actions’ minimum granularity)
  workflow_dispatch: {}     # allow manual runs from the Actions tab

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 4
    env:
      RENDER_HEALTH_URL: https://knowledgebase-chatbot.onrender.com/health
    steps:
      - name: Ping health endpoint
        continue-on-error: true          # don’t fail the workflow if the ping misses
        shell: bash
        run: |
          # Add a little jitter so many repos don’t hit at the same second
          sleep $((RANDOM % 20))

          echo "Pinging: $RENDER_HEALTH_URL"
          # -f: fail on HTTP errors, -sS: silent but show errors, -m: 10s timeout
          curl -fsS -m 10 "$RENDER_HEALTH_URL" || echo "Ping failed (service may be sleeping); will try again next run."
